### ISSUE TITLE
Improve the 'release-process.md' file - Kyma 1.3.0

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/community#313]
**Description**
This is a list of improvements to the [release-process.md](https://github.com/kyma-project/community/blob/master/guidelines/releases/release-process.md) created after the Kyma 1.3.0 release.
* in the [Define Release Jobs](https://github.com/kyma-project/community/blob/master/guidelines/releases/release-process.md#define-release-jobs) section we should move `kyma-github-release.yaml` close to the note about the `presets` array. We should also mention that in the same file the name of `preset-target-commit-1.3` field should be updated as well:
  ``` 
  name: post-rel13-kyma-github-release
      branches:
      - release-1.3
      <<: *job_template
      extra_refs:
      - <<: *test_infra_ref
        base_ref: release-1.3
      labels:
        <<: *job_labels_template
        preset-build-release: "true"
        preset-target-commit-1.3: "true"
   ```
* some of the images do not follow `develop/version` pattern. There are exceptions like [this](https://github.com/kyma-project/kyma/pull/4824/files#diff-f638724a45745ba6f013d2d13ca3572eL38) one where we use `pr/PR-xxxx` naming scheme.
We have to mention that in the docs as well.
* in `test-infra` repository in tests there is the `unsupportedReleases` variable that needs to be updated as well ([example](https://github.com/kyma-project/test-infra/blob/1de12099f24586a829cc5a0f246dbd560b612dd4/development/tools/jobs/kyma/application_connectivity_certs_setup_job_test.go#L13)). We have to mention that in the docs.

**Related issue(s)**
* https://github.com/kyma-project/kyma/issues/4447
