### ISSUE TITLE
Automate release job generation for new releases

### ISSUE THREAD

**Issue by k15r** [kyma-project/community#317]
**Description**

Create a helper script that updates the prow job definitions with new presubmit job for new releases.

**Reasons**

For every new release we need to update our job definitions.
every prow job definition yaml contains presubmit jobs for every new release e.g.:

```
presubmits: # runs on PRs
  kyma-project/kyma:
  - name: pre-rel11-kyma-components-api-controller
    branches:
      - release-1.1
    <<: *job_template
    always_run: true
    extra_refs:
      - <<: *test_infra_ref
        base_ref: release-1.1
    labels:
      <<: *job_labels_template
      preset-build-release: "true"
  - name: pre-rel12-kyma-components-api-controller
    branches:
      - release-1.2
    <<: *job_template
    always_run: true
    extra_refs:
      - <<: *test_infra_ref
        base_ref: release-1.2
    labels:
      <<: *job_labels_template
      preset-build-release: "true"
  - name: pre-rel13-kyma-components-api-controller
    branches:
    - release-1.3
    <<: *job_template
    always_run: true
    extra_refs:
    - <<: *test_infra_ref
      base_ref: release-1.3
    labels:
      <<: *job_labels_template
      preset-build-release: "true"
```

This list of presubmit jobs has to be updated to include a job for the new release and to be cleaned off the oldest of its jobs. The list must not include more than 3 release specific jobs (according to the documentation).

so the script would basically implement this diff:
```diff 
presubmits: # runs on PRs
  kyma-project/kyma:
-  - name: pre-rel11-kyma-components-api-controller
-    branches:
-      - release-1.1
-    <<: *job_template
-    always_run: true
-    extra_refs:
-      - <<: *test_infra_ref
-        base_ref: release-1.1
-    labels:
-      <<: *job_labels_template
-      preset-build-release: "true"
  - name: pre-rel12-kyma-components-api-controller
    branches:
      - release-1.2
    <<: *job_template
    always_run: true
    extra_refs:
      - <<: *test_infra_ref
        base_ref: release-1.2
    labels:
      <<: *job_labels_template
      preset-build-release: "true"
  - name: pre-rel13-kyma-components-api-controller
    branches:
    - release-1.3
    <<: *job_template
    always_run: true
    extra_refs:
    - <<: *test_infra_ref
      base_ref: release-1.3
    labels:
      <<: *job_labels_template
      preset-build-release: "true"
+  - name: pre-rel14-kyma-components-api-controller
+    branches:
+    - release-1.4
+    <<: *job_template
+    always_run: true
+    extra_refs:
+    - <<: *test_infra_ref
+      base_ref: release-1.4
+    labels:
+      <<: *job_labels_template
+      preset-build-release: "true"
```
**Attachments**
