### ISSUE TITLE
Separation of module lifecycle and business logic statuses

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/community#899]
Created on 2024-03-06 by Jan Medrek (@janmedrek).

## Decision log

| Name | Description |
|-----------------------|------------------------------------------------------------------------------------|
| Title | Separation of module lifecycle and business logic statuses. |
| Due date | 2024-03-31 |
| Status | Accepted on 2024-03-31 |
| Decision type | Binary |
| Affected decisions | None |

## Context

In the current design, the "state" of modules is quite blurry - it is a mix of both deployment health coming from the Kyma Lifecycle Manager and business logic status that is monitored by the module operator. This causes the need to synchronize the value of this field and take into consideration multiple factors that do not fall under the same category. The overall situation is that it is not clear what is the current state of both deployment health and the business logic of the module.

## Decision

A clear separation should be introduced between two state types for each module:
- Manifest State - standing for the overall health of K8S resources that the Module consists of. This state is managed solely by the Kyma Lifecycle Manager, it contains information on whether the K8S manifest was applied correctly and deployment is running or not.
- Module State - representing the state of "business logic" of the module. This field is under the complete control of the Module Operator and can be used to communicate the current condition of the module to the User.

Then the following values should be used in the State fields:
- Manifest State
  - Ready - Manifest was applied correctly and the workload is running
  - Processing - Lifecycle Manager waits for the pods to get up/K8S to apply changes
  - Deleting - The manifest is under deletion, most likely waiting for some blocking resource removal
  - Error - There was an issue that is not able to be resolved automatically and a grace period/number of retries was used
- Module State
  - Error - An error or problem has occurred. The message contains actions you need to perform to resolve the issue. Example: You configured an expired certificate.
  - Warning - A statement of fact that alerts you to a potential mistake. You may proceed with your action despite the warning. Example: You configured a certificate which is about to expire
  - Ready - No errors or warnings
  - Deleting/In Progress - Module Operator is performing actions

## Consequences

Module state that is reflected in the Manifest CR's `status.state` field will now be used to represent the Manifest Status. This means that it will only contain information on the success/failure of the k8s resource application in the cluster and whether the deployment remains in a healthy state or not.

The Kyma CR will be also affected in the following ways:
- every module listed in the `status.module` section will contain the `state` field managed by the KLM and representing the Manifest Status
- every module listed in the `status.module` section will contain the reference to the specific Module CR that corresponds to that module
- `status.state` will be an aggregation of the Manifest Statuses of all modules enabled within that Kyma

Then for the "business" status of the modules - the operator should manage the corresponding Module CR and update the `state` field there to indicate the Module Status. This is a field that can be presented to the user to notify them whether the module logic is running smoothly or if some kind of manual action is needed.

There should be a clear recommendation/contract on the values used for the Module Status, including:

As an example, here is the `Warning` status of Eventing CR, which indicates the backend was not specified and the module is not ready to handle events:
```
status:
  activeBackend: ''
  conditions:
    - lastTransitionTime: '2024-03-26T07:01:17Z'
      message: Backend config is not provided. Please specify a backend.
      reason: BackendNotSpecified
      status: 'False'
      type: BackendAvailable
  specHash: 0
  state: Error
```

And a status section from the corresponding Kyma CR, which includes `Ready` for both eventing and overall Kyma state as all the modules were deployed successfully and the workload specified in the Module Manifest runs properly:
```
  modules:
    - channel: fast
      [...]
      name: eventing
      resource:
        apiVersion: operator.kyma-project.io/v1alpha1
        kind: Eventing
        metadata:
          name: eventing
          namespace: kyma-system
      state: Ready
      [...]
  state: Ready
```
