### ISSUE TITLE
Kyma networking

### ISSUE THREAD

**Issue by tmilos77** [kyma-project/community#983]
Created on 2025-04-14 by [Milos Tomic](@tmilos77 ).

## Decision log

| Name | Description |
|-----------------------|------------------------------------------------------------------------------------|
| Title | Creation of the VPC and related network resources by Kyma instead by Gardener |
| Due date | - |
| Status | Proposed on 2025-04-14 |
| Decision type | Binary |
| Affected decisions | ? |

### Problems being solved

* Change conflicts with cloud resources Gardener owns during provisioning of Kyma cloud resources
* Possibility to create multiple Kyma Runtime Clusters in a single VPC

#### Gardener conflicts 

Kyma creates Shoot resources letting Gardener to create network resources. In that mode Gardener behaves as the owner of those resources. During Gardener reconciliations it is checking the status of the cloud resources it created and reacts if a drift is detected. If impossible to heal and correct the drift the Shoot ends up with the error status.

Kyma, through its component CloudManager, provides cloud resource management for its users. Managed cloud resources vary but generally can be aggregated in two groups:
* cloud resources requiring IP endpoints in the VPC Network - NFS, Redis, Databases...
* resources in the cloud provider infrastructure outside the VPC Network that do not need IP address from the VPC Network

All cloud resources provisioned by Kyma are allocated a dedicated subnet (IP address range) outside the CIDR that Gardener allocated for worker nodes. 

Depending on the provider and particular Gardener implementation sometimes it is possible to extend the VPC Network address space so Shoot reconciliation continues working correctly, but sometimes it's impossible due to the conflicts with 
Gardner ownership. 

#### Multiple Kyma Runtime Clusters in a single VPC

Having the [Support for Multiple Kyma Runtime Clusters in a single VPC #18772](https://github.com/kyma-project/kyma/issues/18772) issue on the roadmap, a change is required since Gardener is not able to create multiple shoot clusters in the same VPC Network. 

#### Involved components

![Image](https://github.com/user-attachments/assets/f8142f93-cdfd-4dad-8ecf-17ede1dfa73f)

In existing setup the BTP Service Managed sends a message to Kyma Environment Broker (KEB) with the payload of users intention for a Kyma Runtime Cluster provisioning. The payload holds the information of the nodes CIDR beside the others. The KEB picks the Multi Cloud subscription from Hyperscaler Account Pool (HAP) and creates a `Runtime` CR with the user provided nodes CIDR. Kyma Infrastructure Manager (KIM) reconciles on the `Runtime` CR and creates the `Shoot` CR in the Garden. Once shoot cluster is ready, the KIM creates the `GardenerCluster` CR with the cluster kubeconfig, and marks the `Runtime` CR as ready. When KEB observes the `Runtime` CR as ready, it creates the `Kyma` CR. CloudManager observes the `GardenerCluster` and `Kyma` CRs, reads the additional configuration from the Garden (Shoot, SecretBinding, Secret) and acts upon the cloud provider to extend the VPC network address space, provision cloud resources, and assign them IP addresses from the extended space.

---

## Decision

Kyma will create the VPC and manage its topology, giving to the Gardener just the identifiers of the network resources it needs, like IDs of the Subnets where worker node VMs should be provisioned.

Lacking the appropriate Kyma API exceeding the lifecycle of a single SKR (aka Kyma Control Center), the only API Kyma was left with, though not ideal, is the BTP Service Manager API served by KEB. It will be extended with the network related user preferences, such as the VPC name and the overall address space.

### User experience in BTP

Users in BTP Kyma broker message parameters for SKR provisioning can specify
* to create new network  
* use existing network

The network topology includes:
* overall network address space to be used
* a subset of the overall address space to use for SKR worker nodes

#### Create SKR with new network

```yaml
# SKR-A
# existing specifications for the new SKR ranges
networking:
  # new specifications for the whole VPC
  vpc:
    name: "my-vpc-1"
    # the whole vpc address space
    cidrs: ["10.250.0.0/15", "10.252.0.0/15"]
  # old/existing networking config
  # must be a subset of the whole vpc address space
  # that is specified in vpc.cidr
  nodes: "10.250.0.0/16", 
  # overlay network outside the vpc address space
  pods: "10.96.0.0/13",
  services: "10.104.0.0/13"
```

This makes a new VPC address space:
* `10.250.0.0/16` - given to SKR-A
* `10.251.0.0/16`
* `10.252.0.0/16`
* `10.253.0.0/16`

#### Create SKR with existing network

```yaml
# SKR-B
# existing specifications for the new SKR ranges
networking:
  vpc:
    # only name of existing vpc is required
    # no need to repeat specifications of the existing network
    name: "my-vpc-1"
  nodes: "10.252.0.0/16", 
  pods: "10.96.0.0/13",
  services: "10.104.0.0/13"
```

This adds new SKR to the existing VPC address space:
* `10.250.0.0/16` - given to SKR-A
* `10.251.0.0/16`
* `10.252.0.0/16` - given to SKR-B
* `10.253.0.0/16`

#### API Constraints

Once VPC network is created user can not reduce its size nor modify any of the given and allocated CIDRs. The network can only be extended by adding more CIDRs to it, but only when a new SKR is created due to the API constraint.

> [!NOTE]  
> The broker protocol should be investigated if it is possible to communicate validation messages back to the BTP Cockpit users.

### New execution flow

The change affects KEB, KIM and CloudManager and requires a new KCP networking API. 

![Image](https://github.com/user-attachments/assets/92fa597b-1cf6-4b14-b3ce-893450f11bf6)

* KEB finds the appropriate subscription from the HAP
* KEB finds the corresponding `Network` CR
  * If none found
    * KEB creates a new `Network` CR
    * CM reconciles the `Network` CR and in the cloud provider it creates: 
      * VPC network 
* KEB finds the corresponding `Cluster` CR
  * If none found
    * KEB creates a new `Cluster` CR
    * CM reconciles the `Cluster` CR and in the cloud provider it creates:
      * Network resources required for the cluster:
        * Subnets
        * Internet/NAT gateways
        * Routing tables
        * ...
* KEB creates Runtime CR with network and subnets identifiers
* KIM reconciles the Runtime CR and creates Shoot CR with the given network and subnets identifiers
* Gardener reconciles the Shoot CR and creates VMs in the given existing subnets
* KIM creates `GardenerCluster` CR
* KEB creates the `Kyma` CR
* User creates some cloud resource CR in the SKR
* CM reconciles some cloud resource CR in the SKR and creates cloud resources in the cloud provider and joins it to already allocated VPC address space.

#### Network 

The `Network` kind represents the user intention of having a cloud provider VPC network of specified address space.
* defines VPC address space
* specifies the HAP subscription
* specifies the region

```yaml
apiVersion: networking.kyma-project.io
kind: Network
metadata:
  name: net-1
spec:
  name: my-vpc-1
  cidrs: ["10.250.0.0/15", "10.252.0.0/15"]
  subscription: subscription-00314
  region: europe-central-1
status:
  id: some-vpc-id
```

Reconciles into a cloud provider VPC network.

#### Cluster Range

The `Cluster` kind represents user intention of having a Kyma runtime cluster in the specified address space.
* defines the cluster address space
* specifies the Network and inherits the region 

```yaml
apiVersion: networking.kyma-project.io
kind: Cluster
spec:
  network: net-1
  cidr: 10.250.0.0/16
  region: europe-cental-1
status:
  subnets:
    - zone: europe-cental-1a
      id: cluster-subnet-id-a  # given to Gardener for worker VMs
    - zone: europe-cental-1b
      id: cluster-subnet-id-b  # given to Gardener for worker VMs
    - zone: europe-cental-1c
      id: cluster-subnet-id-c  # given to Gardener for worker VMs
  natGateways:
    - ip: 31.32.33.34
```

Reconciles into cloud provider resources required for the Kyma runtime cluster:
* Subnets
* Internet/NAT gateways
* Routing tables
* etc

### Sharing of the Kyma cloud resources

Kyma cloud range, where Kyma cloud resources are allocated, being just a segment of the VPC address space is accessible from each SKR in that single VPC network. A single Kyma cloud resource manifest, ie NfsVolume, is created in one SKR, and its bindings like PersistentVolume and PersistentVolumeClaim is created in that same SKR. Practically that NFS IP address is reachable from the other SKRs in the same VPC, but since the provisioning API is bound to the SKR, the user experience will be limited to a single cluster. 

Having an API transcending lifecycle of SKR would solve the issue and would be able to show precise network and resources state, as well as to tweak accessibility to/from different network partitions.

### Kyma cloud resources lifecycle

The lifecycle of Kyma cloud resources (NFS, Redis, VpcPeering), as so far, is bound to the lifecycle of the SKR where they are created. Once SKR is deleted, also all cloud resources created from that SKR are deleted (although they might be used in other SKRs in the same VPC).

## Open topics

* BTP broker protocol validation messages communicated back to user
* Alternate API service, separate from Kyma Runtime provisioning, that will
  be used for Kyma network management with more capabilities
